### ISSUE TITLE
Expanded example information?

### ISSUE THREAD

**Issue by gmgarrison** [Label305/DocxExtractor#5]
I THINK I'd like to use this library but I can't tell for sure because I can't tell exactly how it works.

Can you expand the example in the readme file to describe an entire use case? It's not clear to me, for example, how to specify what text I want to search for and what text I want to replace it with. It's also not at all clear what simple-extracted.docx contains.

Thank you!

**Comment by tscheepers** [comment]
Hey @gmgarrison, I've just updated the readme for you.

We need to have this special `simple-extracted.docx` file to know where to later inject the altered text back into. The `simple-injected.docx` is the final file after the modification.
